services:
  mongodb:
    image: mongo:4.4-focal
    container_name: mongodb
    restart: always
#    command: --auth --config /etc/mongo/mongod.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: hibernate_ogm
      TZ: Asia/Taipei
#    volumes: 
#      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#      - ./database/configdb:/data/configdb
#      - ./database/data:/data/db
#      - ./mongod.conf:/etc/mongo/mongod.conf
    ports: 
      - '27017:27017'
    networks:
      - mongodb_network
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - 8081:8081
    networks:
      - mongodb_network
    depends_on:
      - mongodb
networks:
  mongodb_network:
    driver: bridge
    name: mongo-network      